TensorRT OSS 21.02 release
NVIDIA/TensorRT pull request #1038
Opened 2021-02-01 10:16 UTC by rajeevsrao

Signed-off-by: Rajeev Rao <rajeevrao@nvidia.com>

2021-02-01 13:22 UTC, ttyio approved these changes

2021-02-01 13:24 UTC, ttyio commented
@rajeevsrao  I see some python temp file *.pyc is added in the PR

2021-02-01 13:25 UTC, ttyio requested changes
Remove  demo/BERT/helpers/__pycache__/

2021-02-01 17:41 UTC, kevinch-nv requested changes

2021-02-01 17:41 UTC, kevinch-nv commented on demo/BERT/README.md
> +  * [onnx](https://pypi.org/project/onnx/1.6.0/) (tested 1.7.0)
Link should be updated here

2021-02-01 17:41 UTC, kevinch-nv commented on quickstart/IntroNotebooks/onnx_helper.py
> +import numpy as np
missing cp header

2021-02-01 17:41 UTC, kevinch-nv commented on quickstart/IntroNotebooks/helper.py
> +from tensorflow.python.compiler.tensorrt import trt_convert as tf_trt
cp header

2021-02-01 17:41 UTC, kevinch-nv commented on quickstart/IntroNotebooks/benchmark.py
> +import time
cp header

2021-02-01 17:41 UTC, kevinch-nv commented on quickstart/IntroNotebooks/Additional Examples/helper.py
> +from tensorflow.python.compiler.tensorrt import trt_convert as tf_trt
cp header

2021-02-01 18:06 UTC, kevinch-nv approved these changes

2021-02-03 00:17 UTC, ttyio approved these changes

2021-02-05 22:22 UTC, merged