Fixing onnxruntime-1.10 compatibility
NVIDIA/TensorRT pull request #1788
Opened 2022-02-09 21:30 UTC by borisfom

Signed-off-by: Boris Fomitchev <bfomitchev@nvidia.com>

2022-02-10 16:34 UTC, kevinch-nv requested changes

2022-02-10 20:00 UTC, pranavm-nvidia commented on tools/onnx-graphsurgeon/onnx_graphsurgeon/ir/graph.py
> +        self.ort_providers = ['CUDAExecutionProvider']
+1

Alternatively can set to `onnxrt.get_available_providers()`

2022-02-10 21:03 UTC, borisfom commented on tools/onnx-graphsurgeon/onnx_graphsurgeon/ir/graph.py
> +        self.ort_providers = ['CUDAExecutionProvider']
Well, there is no better scope to share between two methods ... fixed by using CPU provider inline.

2022-02-10 21:05 UTC, pranavm-nvidia approved these changes

2022-02-10 21:06 UTC, pranavm-nvidia commented on tools/onnx-graphsurgeon/onnx_graphsurgeon/ir/graph.py
> +        self.ort_providers = ['CUDAExecutionProvider']
It could be scoped to `fold_constants`, but it's fine to hard-code for now. We can refactor in the future if needed

2022-02-10 22:49 UTC, kevinch-nv approved these changes

2022-02-23 15:43 UTC, pranavm-nvidia commented
@borisfom can we merge this now?

2022-02-23 17:19 UTC, merged